### PR TITLE
feat: Add support for /getPower metrics

### LINKED ISSUE #14: getPower exports to prometheus?
It might be nice to include getPower exports to prometheus, for graphing power stats, in addition to production stats:

https://docs.ficsit.app/ficsitremotemonitoring/latest/json/Read/getPower.html

### PR DESCRIPTION
**Pull request by featheredtoast**
Adds support for `/getPower` to prometheus exporter for monitoring of circuit power and battery stats.
Updates prometheus scraping port for FRM from 8090 to 8080.
Allows tests to be run in other environments with OS targeting on the prometheus wrapper.
Update ProdPercent and ConsPercent expectation as FRM passes these in as floats
Fixing tests: Allow more than one test suite to be run by removing fatal logger.

closes #14

### CODE REVIEW

**Comment by AP-Hunt** [comment]
Hi @featheredtoast, thanks for putting your time into making the change, I appreciate that. The code looks excellent, exactly as I'd have done it myself.

Before I merge it, could I ask you to run `make readme` to update the readme with all the new metrics you've added, please?

**Comment by featheredtoast** [comment]
@AP-Hunt readme updated and commit squashed in

**Review by AP-Hunt — APPROVED** [review]
Thanks for that. I'll merge this now and cut a new release shortly.

**Comment by featheredtoast** [comment]
Not a problem - and many thanks for your ongoing work on this - it's a great addition to the base game. Cheers!

**Pull request merged**
