### PR TITLE
exporter: add global resource sink metrics

### PR DESCRIPTION
**Pull request by sinuscosinustan**
FRM exposes the amount of coupons and points via `/getResourceSink` and allows to monitor the total amount of points per minute with `rate`.

### CODE REVIEW

**Comment by AP-Hunt** [comment]
Hi @sinuscosinustan, thanks for the contribution, I appreciate the time and effort that's gone in. If you can address the linting failure I'd be happy to approve and merge this.

**Comment by sinuscosinustan** [comment]
@AP-Hunt done

**Comment by AP-Hunt** [comment]
@sinuscosinustan Thanks again for the contribution. I've cut a new release with your changes: 1.3.2

**Comment by featheredtoast** [comment]
@sinuscosinustan just following up, there are two sink types, one for resources and one for exploration. 1.3.3 addresses this and splits the metrics with a `sink_type` label.

**Pull request merged**
