### PR TITLE
1.0 fixes, adds ability to monitor multiple servers, and future save file

### PR DESCRIPTION
**Pull request by featheredtoast**
Allow for collections to parameterize server name and save file.

Add new -hostnames arg that is a comma separated value list of servers to watch and update, EG `-hostnames server1:8080,server2:9090,server3:8080` - this is exposed as a `url` label to metrics so interested parties can watch multiple servers at once.

`save_name` label is "default" for now until FRM can provide a save name.

Also fix up some discrepancies with ficsit remote monitoring's values. We still do not have power values back yet but they're coming

### CODE REVIEW

**Comment by AP-Hunt** [comment]
Thanks for this @featheredtoast. I'm overall happy with the proposed changes and the rational, there's just one doc block to add.

**Comment by featheredtoast** [comment]
Just pushed a few fixes, wanted more stuff configurable via env vars. gonna test a little more but it's looking good now. will update docs.

**Comment by featheredtoast** [comment]
just updating, FRM has a few more updates to make it more 1.0 compatible, so I'll update this PR with those.

Meanwhile, would you mind terribly much if we updated how readme generation is done? From what I understand, we're using a golang template to generate the table, and then a batch script to search+replace the readme template... Can we update this to just use golang templates through-and-through?

That way I'd be able to generate new readme tables on non-windows, which is my primary daily driver

**Comment by AP-Hunt** [comment]
Yeah I'm completely fine with that. I don't use Windows for anything anymore, so I really should update the tooling full stop.

**Comment by featheredtoast** [comment]
All good, I *think* I'm almost done here, FRM 1.2(?) has become much more stable and I don't anticipate this mod needing too many more changes on this.

I'll ping you once I update the tooling steps and then this should be good to merge in

**Comment by AP-Hunt** [comment]
Thanks for all your work on this @featheredtoast. I don't have the capacity to test these changes, so I'm going to have to trust that they work.

I've reviewed the non-FRM specific bits though, and I'm happy with them.

I'll merge this and cut a release.

**Pull request merged**
